openapi: 3.0.3
info:
  title: 认证业务域 API 聚合
  version: 1.0.0
  description: 认证相关的API聚合，包括用户认证、权限管理、会话管理等功能

paths:
  # 基础架构模块 - 认证相关API
  /api/v1/auth/login:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1login'
  /api/v1/auth/logout:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1logout'
  /api/v1/auth/refresh:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1refresh'
  /api/v1/auth/check-permission:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1check-permission'
  /api/v1/auth/sessions:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1sessions'
  /api/v1/auth/sessions/{session_id}:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1sessions~1{session_id}'

  # 用户与权限管理模块 - 用户管理API
  /api/v1/users:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1users'
  /api/v1/users/{id}:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1users~1{id}'
  /api/v1/users/{id}/status:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1users~1{id}~1status'
  /api/v1/users/{id}/reset-password:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1users~1{id}~1reset-password'
  /api/v1/users/batch-import:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1users~1batch-import'
  /api/v1/users/batch-status:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1users~1batch-status'
  /api/v1/users/{id}/roles:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1users~1{id}~1roles'
  /api/v1/users/{userId}/roles/{roleId}:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1users~1{userId}~1roles~1{roleId}'
  /api/v1/users/{id}/permissions:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1users~1{id}~1permissions'
  /api/v1/users/{id}/sessions:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1users~1{id}~1sessions'

  # 角色管理API
  /api/v1/roles:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1roles'
  /api/v1/roles/{id}:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1roles~1{id}'
  /api/v1/roles/{id}/permissions:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1roles~1{id}~1permissions'
  /api/v1/roles/{roleId}/permissions/{permissionId}:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1roles~1{roleId}~1permissions~1{permissionId}'

  # 基础权限管理API（REQ-022）
  /api/v1/permissions:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions'

  # 部门管理API
  /api/v1/departments:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1departments'
  /api/v1/departments/{id}:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1departments~1{id}'
  /api/v1/departments/{id}/users:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1departments~1{id}~1users'

  # 会话管理API
  /api/v1/sessions:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1sessions'
  /api/v1/sessions/{sessionId}:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1sessions~1{sessionId}'
  /api/v1/sessions/batch-logout:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1sessions~1batch-logout'

  # 审计日志API
  /api/v1/audit-logs:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1audit-logs'
  /api/v1/audit-logs/export:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1audit-logs~1export'

  # 权限检查API
  /api/v1/auth/check-permission:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1auth~1check-permission'
  /api/v1/auth/batch-check-permissions:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1auth~1batch-check-permissions'
  /api/v1/auth/mfa/verify:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1auth~1mfa~1verify'

  # 外部身份源API
  /api/v1/external-identity-sources:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1external-identity-sources'

  # 权限模板API
  /api/v1/permission-templates:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1permission-templates'
  /api/v1/permission-templates/{id}/apply:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1permission-templates~1{id}~1apply'

  # 资源权限管理模块API（REQ-021）
  # 权限验证
  /api/v1/permissions/verify:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1verify'
  /api/v1/permissions/batch-verify:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1batch-verify'

  # 权限策略管理
  /api/v1/permissions/policies:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1policies'
  /api/v1/permissions/policies/{id}:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1policies~1{id}'

  # 权限分配管理
  /api/v1/permissions/assignments:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1assignments'
  /api/v1/permissions/assignments/{id}:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1assignments~1{id}'
  /api/v1/permissions/batch-assign:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1batch-assign'
  /api/v1/permissions/batch-revoke:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1batch-revoke'

  # 权限审计
  /api/v1/permissions/audit-logs:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1audit-logs'
  /api/v1/permissions/audit-logs/{id}:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1audit-logs~1{id}'
  /api/v1/permissions/audit-reports:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1audit-reports'

  # 权限统计
  /api/v1/permissions/statistics/usage:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1statistics~1usage'

  # 基础架构模块API（REQ-001）
  # 认证API
  /api/v1/auth/login:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1login'
  /api/v1/auth/logout:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1logout'
  /api/v1/auth/refresh:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1refresh'
  /api/v1/auth/sessions:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1sessions'
  /api/v1/auth/sessions/{session_id}:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1sessions~1{session_id}'

  # 管理员API
  /api/v1/admin/tenants:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1admin~1tenants'
  /api/v1/admin/configs:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1admin~1configs'
  /api/v1/admin/configs/{key}:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1admin~1configs~1{key}'

  # 审计API
  /api/v1/audit/logs:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1audit~1logs'

  # 内部API
  /api/v1/internal/auth/verify:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1internal~1auth~1verify'
  /api/v1/internal/tenants/{id}:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1internal~1tenants~1{id}'

  # 健康检查API
  /api/v1/health:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1health'

components:
  # 引用全局通用组件
  schemas:
    ApiResponse:
      $ref: '../global-api-index.yaml#/components/schemas/ApiResponse'
    PagedResponse:
      $ref: '../global-api-index.yaml#/components/schemas/PagedResponse'
    ErrorResponse:
      $ref: '../global-api-index.yaml#/components/schemas/ErrorResponse'
