openapi: 3.0.3
info:
  title: 认证业务域 API 聚合
  version: 1.0.0
  description: 认证相关的API聚合，包括用户认证、权限管理、会话管理等功能

paths:
  # 基础架构模块 - 认证相关API
  /api/v1/auth/login:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1login'
  /api/v1/auth/logout:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1logout'
  /api/v1/auth/refresh:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1refresh'
  /api/v1/auth/check-permission:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1check-permission'
  /api/v1/auth/sessions:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1sessions'
  /api/v1/auth/sessions/{session_id}:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1api~1v1~1auth~1sessions~1{session_id}'

  # 用户与权限管理模块 - 用户管理API
  /api/v1/users:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1users'
  /api/v1/users/{id}:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1users~1{id}'

  # 角色管理API
  /api/v1/roles:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1roles'
  /api/v1/roles/{id}:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1roles~1{id}'

  # 基础权限管理API（REQ-022）
  /api/v1/permissions:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions'

  # 资源权限管理模块API（REQ-021）
  # 权限验证
  /api/v1/permissions/verify:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1verify'
  /api/v1/permissions/batch-verify:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1batch-verify'

  # 权限策略管理
  /api/v1/permissions/policies:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1policies'
  /api/v1/permissions/policies/{id}:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1policies~1{id}'

  # 权限分配管理
  /api/v1/permissions/assignments:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1assignments'
  /api/v1/permissions/assignments/{id}:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1assignments~1{id}'
  /api/v1/permissions/batch-assign:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1batch-assign'
  /api/v1/permissions/batch-revoke:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1batch-revoke'

  # 权限审计
  /api/v1/permissions/audit-logs:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1audit-logs'
  /api/v1/permissions/audit-logs/{id}:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1audit-logs~1{id}'
  /api/v1/permissions/audit-reports:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1audit-reports'

  # 权限统计
  /api/v1/permissions/statistics/usage:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1api~1v1~1permissions~1statistics~1usage'

components:
  # 引用全局通用组件
  schemas:
    ApiResponse:
      $ref: '../global-api-index.yaml#/components/schemas/ApiResponse'
    PagedResponse:
      $ref: '../global-api-index.yaml#/components/schemas/PagedResponse'
    ErrorResponse:
      $ref: '../global-api-index.yaml#/components/schemas/ErrorResponse'
