openapi: 3.0.3
info:
  title: 知识库业务域 API 聚合
  version: 1.0.0
  description: 知识库管理相关的API聚合，包括知识文章管理、分类管理、搜索功能、版本控制等功能

paths:
  # 知识文章管理API
  /api/v1/knowledge/articles:
    $ref: '../modules/REQ-005-知识库管理系统/openapi.yaml#/paths/~1api~1v1~1knowledge~1articles'
  /api/v1/knowledge/articles/{id}:
    $ref: '../modules/REQ-005-知识库管理系统/openapi.yaml#/paths/~1api~1v1~1knowledge~1articles~1{id}'
  /api/v1/knowledge/articles/{id}/versions:
    $ref: '../modules/REQ-005-知识库管理系统/openapi.yaml#/paths/~1api~1v1~1knowledge~1articles~1{id}~1versions'

  # 知识搜索API
  /api/v1/knowledge/search:
    $ref: '../modules/REQ-005-知识库管理系统/openapi.yaml#/paths/~1api~1v1~1knowledge~1search'
  /api/v1/knowledge/search/suggest:
    $ref: '../modules/REQ-005-知识库管理系统/openapi.yaml#/paths/~1api~1v1~1knowledge~1search~1suggest'

  # 分类管理API
  /api/v1/knowledge/categories:
    $ref: '../modules/REQ-005-知识库管理系统/openapi.yaml#/paths/~1api~1v1~1knowledge~1categories'

components:
  schemas:
    # 引用全局通用组件
    ApiResponse:
      $ref: '../global-api-index.yaml#/components/schemas/ApiResponse'
    PagedResponse:
      $ref: '../global-api-index.yaml#/components/schemas/PagedResponse'
    ErrorResponse:
      $ref: '../global-api-index.yaml#/components/schemas/ErrorResponse'
