openapi: 3.0.3
info:
  title: Unotification 业务域 API 聚合
  version: 1.0.0
paths:
  /api/v1/notifications/send:
    $ref: '../modules/REQ-011-通知与消息系统/openapi.yaml#/paths/~1api~1v1~1notifications~1send'
  /api/v1/notifications:
    $ref: '../modules/REQ-011-通知与消息系统/openapi.yaml#/paths/~1api~1v1~1notifications'
