openapi: 3.0.3
info:
  title: Uportal 业务域 API 聚合
  version: 1.0.0
paths:
  /api/v1/dashboard/configs:
    $ref: '../modules/REQ-002-工作台与仪表板/openapi.yaml#/paths/~1api~1v1~1dashboard~1configs'
  /api/v1/dashboard/widgets:
    $ref: '../modules/REQ-002-工作台与仪表板/openapi.yaml#/paths/~1api~1v1~1dashboard~1widgets'
  /api/v1/dashboard/statistics/overview:
    $ref: '../modules/REQ-002-工作台与仪表板/openapi.yaml#/paths/~1api~1v1~1dashboard~1statistics~1overview'
