openapi: 3.0.3
info:
  title: Usystem 业务域 API 聚合
  version: 1.0.0
paths:
  /系统管理模块:
    $ref: '../modules/REQ-010-系统管理模块/openapi.yaml#/paths/~1系统管理模块'
  /系统设置:
    $ref: '../modules/REQ-008-系统设置/openapi.yaml#/paths/~1系统设置'
  /运维管理:
    $ref: '../modules/REQ-009-运维管理/openapi.yaml#/paths/~1运维管理'
