openapi: 3.0.3
info:
  title: Uticket 业务域 API 聚合
  version: 1.0.0
paths:
  /工单管理系统:
    $ref: '../modules/REQ-003-工单管理系统/openapi.yaml#/paths/~1工单管理系统'
  /智能派单系统:
    $ref: '../modules/REQ-004-智能派单系统/openapi.yaml#/paths/~1智能派单系统'
