openapi: 3.0.3
info:
  title: 工作流业务域 API 聚合
  version: 1.0.0
  description: 工作流相关的API聚合，包括工作流引擎、流程管理、任务管理等功能
paths:
  /api/v1/workflows/definitions:
    $ref: ../modules/REQ-014-工作流引擎系统/openapi.yaml#/paths/~1api~1v1~1workflows~1definitions
  /api/v1/workflows/definitions/{id}:
    $ref: ../modules/REQ-014-工作流引擎系统/openapi.yaml#/paths/~1api~1v1~1workflows~1definitions~1{id}
  /api/v1/workflows/definitions/{id}/publish:
    $ref: ../modules/REQ-014-工作流引擎系统/openapi.yaml#/paths/~1api~1v1~1workflows~1definitions~1{id}~1publish
  /api/v1/workflows/instances/start:
    $ref: ../modules/REQ-014-工作流引擎系统/openapi.yaml#/paths/~1api~1v1~1workflows~1instances~1start
  /api/v1/workflows/instances:
    $ref: ../modules/REQ-014-工作流引擎系统/openapi.yaml#/paths/~1api~1v1~1workflows~1instances
  /api/v1/workflows/instances/{instance_id}:
    $ref: ../modules/REQ-014-工作流引擎系统/openapi.yaml#/paths/~1api~1v1~1workflows~1instances~1{instance_id}
  /api/v1/workflows/instances/{instance_id}/suspend:
    $ref: ../modules/REQ-014-工作流引擎系统/openapi.yaml#/paths/~1api~1v1~1workflows~1instances~1{instance_id}~1suspend
  /api/v1/workflows/instances/{instance_id}/resume:
    $ref: ../modules/REQ-014-工作流引擎系统/openapi.yaml#/paths/~1api~1v1~1workflows~1instances~1{instance_id}~1resume
  /api/v1/workflows/tasks/pending:
    $ref: ../modules/REQ-014-工作流引擎系统/openapi.yaml#/paths/~1api~1v1~1workflows~1tasks~1pending
  /api/v1/workflows/tasks/{task_id}:
    $ref: ../modules/REQ-014-工作流引擎系统/openapi.yaml#/paths/~1api~1v1~1workflows~1tasks~1{task_id}
  /api/v1/workflows/tasks/{task_id}/complete:
    $ref: ../modules/REQ-014-工作流引擎系统/openapi.yaml#/paths/~1api~1v1~1workflows~1tasks~1{task_id}~1complete
  /api/v1/workflows/tasks/{task_id}/delegate:
    $ref: ../modules/REQ-014-工作流引擎系统/openapi.yaml#/paths/~1api~1v1~1workflows~1tasks~1{task_id}~1delegate
  /api/v1/workflows/statistics:
    $ref: ../modules/REQ-014-工作流引擎系统/openapi.yaml#/paths/~1api~1v1~1workflows~1statistics
components:
  schemas:
    ApiResponse:
      $ref: ../global-api-index.yaml#/components/schemas/ApiResponse
    PagedResponse:
      $ref: ../global-api-index.yaml#/components/schemas/PagedResponse
    ErrorResponse:
      $ref: ../global-api-index.yaml#/components/schemas/ErrorResponse
