openapi: 3.0.3
info:
  title: Uauth 业务域 API 聚合
  version: 1.0.0
paths:
  /基础架构模块:
    $ref: '../modules/REQ-001-基础架构模块/openapi.yaml#/paths/~1基础架构模块'
  /用户与权限管理模块:
    $ref: '../modules/REQ-022-用户与权限管理模块/openapi.yaml#/paths/~1用户与权限管理模块'
  /资源权限管理模块:
    $ref: '../modules/REQ-021-资源权限管理模块/openapi.yaml#/paths/~1资源权限管理模块'
