openapi: 3.0.3
info:
  title: IT运维门户系统 API
  version: 1.0.0
  description: 全局 API 入口文档（聚合所有业务域）
paths: {}
x-domains:
  - name: auth
    $ref: './domains/auth-domain.yaml'
  - name: ticket
    $ref: './domains/ticket-domain.yaml'
  - name: engineer
    $ref: './domains/engineer-domain.yaml'
  - name: knowledge
    $ref: './domains/knowledge-domain.yaml'
  - name: customer
    $ref: './domains/customer-domain.yaml'
  - name: notification
    $ref: './domains/notification-domain.yaml'
  - name: portal
    $ref: './domains/portal-domain.yaml'
  - name: integration
    $ref: './domains/integration-domain.yaml'
  - name: finance
    $ref: './domains/finance-domain.yaml'
  - name: system
    $ref: './domains/system-domain.yaml'
  - name: analytics
    $ref: './domains/analytics-domain.yaml'
  - name: workflow
    $ref: './domains/workflow-domain.yaml'
  - name: experience
    $ref: './domains/experience-domain.yaml'
  - name: client
    $ref: './domains/client-domain.yaml'
  - name: data
    $ref: './domains/data-domain.yaml'

components:
  schemas:
    # 通用响应Schema
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          description: 响应状态码
          example: 200
        message:
          type: string
          description: 响应消息
          example: "操作成功"
        data:
          type: object
          description: 响应数据
        timestamp:
          type: string
          format: date-time
          description: 响应时间
          example: "2024-08-14T15:30:00Z"

    PagedResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: object
              properties:
                total:
                  type: integer
                  description: 总记录数
                  example: 100
                page:
                  type: integer
                  description: 当前页码
                  example: 1
                size:
                  type: integer
                  description: 每页大小
                  example: 20
                items:
                  type: array
                  description: 数据列表
                  items:
                    type: object

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: 错误状态码
          example: 400
        message:
          type: string
          description: 错误消息
          example: "请求参数错误"
        error:
          type: string
          description: 错误详情
          example: "用户名不能为空"
        timestamp:
          type: string
          format: date-time
          description: 错误时间
          example: "2024-08-14T15:30:00Z"

  responses:
    BadRequest:
      description: 请求参数错误
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: 未认证或认证失败
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Forbidden:
      description: 权限不足
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: 资源不存在
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Conflict:
      description: 资源冲突
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: 服务器内部错误
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
